### ISSUE TITLE
add new options "ctags args"

### ISSUE THREAD

**Issue by Fmajor** [nicolashainaux/symbols-tree-nav#13]
can you add a new option "ctags args"?

i persuaded the Universal Ctags to add a new Vue parser, but now as it is still a experimental feature, i need to use `ctags --extras=+g` command to use it.

Or can you add feature to use different command args for different type of file?
Or even more, can you add more configurations like
[tagbar](https://github.com/majutsushi/tagbar) in vim to have more control in the tree-view?
```
let g:tagbar_type_vue = {
   \ 'ctagstype' : 'mvue',
   \ 'ctagsbin'  : 'ctags',
   \ 'ctagsargs' : '',
   \ 'kinds' : [
       \ 't:Template:0:0',
       \ 'c:vue-command:0:0',
       \ 's:Script:0:0',
       \ 'v:variables:0:0',
       \ 'f:function:0:0',
       \ 'p:property:0:0',
       \ 'e:export:0:0',
   \ ],
   \ 'sro'        : '.',
   \ 'kind2scope' : {
       \ 't' : 'template',
       \ 's' : 'script',
       \ 'p' : 'property',
       \ 'e' : 'export',
   \ },
   \ 'scope2kind' : {
       \ 'template' : 't',
       \ 'script'   : 's',
       \ 'property' : 'p',
       \ 'export'   : 'e',
   \ },
   \ 'sort': 0
\}

```

**Comment by nicolashainaux** [comment]
I do not have much time at the moment. I will try to have a look (as well as add some other new features that are waiting). The easiest seems to add the option `ctags --extras=+g`, don't know about the rest, though it looks interesting (does it allow to create tree views with more levels easier?).

Also, I don't know if the languages you need are supported by this other project, but you might want to check it too: https://github.com/alibaba/structure-view

**Comment by Fmajor** [comment]
the new vue parser generate the same tags as javascript, so it must be supported.
please first add the "ctags args" config, i think it is not very difficult (just concatenate another string after the $ctagsPath before spawn it)

**Comment by nicolashainaux** [comment]
As the PR has been merged and the option now belongs to the published package, I close this. Please reopen it as needed.
