### ISSUE TITLE
Improve markdown support

### ISSUE THREAD

**Issue by nicolashainaux** [nicolashainaux/symbols-tree-nav#2]
Continuation of the discussion started [here](https://github.com/xndcn/symbols-tree-view/pull/138).

**Comment by liuderchi** [comment]
taking previous screenshot as example
![screenshot from 2016-11-21 10 47 47](https://cloud.githubusercontent.com/assets/4994705/20469091/1d6c2d4c-afd8-11e6-9c94-409038e74289.png)

Maybe we can start from these tweaks to understand more about this package

1. extend current parser (or use custom one) to parse list item beginning with minus sign or asterisk 
```markdown
- item foo
* item bar
- item three
```

2. support custom icon in the symbol tree (e.g. font-awesome, atom icon in [styleguide](https://github.com/atom/styleguide))

**Comment by nicolashainaux** [comment]
1. Well, haven't found any ctags parser for markdown (only a small project available on github: markdown2ctags). Couldn't actually find an official list of languages supported by universal ctags. From the information available [here](https://en.wikipedia.org/wiki/Ctags#Variants_of_ctags), it might make sense to use alternative parsers for Haskell and javascript, but not for any other language, at the moment.
So, in order to better parse markdown, the best option seems to write the correct regex rules (i.e. extend current parser; interesting point being that both exuberant and universal ctags use the same rules).

2. For custom icons, maybe the most simple solution would require the user to replace the icons/ folder by its own icons/ folder? About icons, I thought it would be interesting to introduce new icons, that we could use more specifically for markdown (though the ones you chose look already great). But it requires to design new ones...

**Comment by liuderchi** [comment]
> 1. in order to better parse markdown, ... to write correct regex rules ...

Agree with that.

One reference for markdown regex rules: [atom/language-gfm](https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson).

Actually Atom has it's own architecture to parse different languages.
It adds class attribute to 'text' (as html element) and then color it via CSS.

This gives me an inspiration about building a symbols-tree using DOM queries. Is that possible?
(Maybe it's irrelevant to the topic since we are now under ctags architecture.)

**Comment by nicolashainaux** [comment]
> This gives me an inspiration about building a symbols-tree using DOM queries. Is that possible?

I don't know, but if this means rewriting a parser from scratch, this is certainly interesting but harder to develop and maintain over time than using an external parser.

I found out some things:
- the regex rules override the ones that are already built-in in the parser, or provide rules for languages yet unknown from the parser
- what mistake I did when adding support for R language recently, and corrected it (not yet pushed)
- how to add an icon (though my icon doesn't show up completely properly, it works, it's a try for R language's library)

I did add a rule to match libraries in R language rules.

I'll add a dev branch so I can push some relevant commits without polluting master.

But haven't found yet whether regex rules can be used to settle a hierarchy...

Useful site to explore regex rules is https://regex101.com/ though I couldn't make the test strings match (it's not for ctags use I guess), but to understand or remind what syntax/part matches what.

**Comment by nicolashainaux** [comment]
So, the last commit on master is the correction for R language; the commit on dev contains the addition of a "library" icon. I created the svg just by copying the namespace one and changing the letter to L (with inkscape. When opened up in an image viewer, it's correct. But when I upload it on icomoon.io, the letter disappears, no idea why. Must be something wrong in my inkscape file, but have still to explore to discover what. Once this is correct, it'll be easy to add icons for markdown categories.

**Comment by nicolashainaux** [comment]
How to setup a hierarchy can apparently be done using the scope flags (available for universal ctags, but not exuberant ctags). Documentation here http://docs.ctags.io/en/latest/optlib.html#scope-tracking-in-a-regex-parser
I've tried on this file: https://raw.githubusercontent.com/deltaluca/nape/master/graph-gen/Graph.hx (because there are classes and functions in haxe, according to the regex in .ctags file) and added `{scope=ref}` at the end of function and variable regexes, added `{scope=set}` at the end of the class regex line and got the functions folded inside classes. Not everything is right, but I think the regex do not detect all variables correctly.
No idea if it is possible to have multiple levels folded, but it's worth the try!

**Comment by nicolashainaux** [comment]
> No idea if it is possible to have multiple levels folded, but it's worth the try!

It certainly is, as I do have python files with nested classes and the folding is done well.

I could correctly add new icons. In order to do that, with inkscape, the best is to start from a copy of another icon (so you get directly the right dimensions) and modify it. Important thing to do when you're done is to turn your shapes (text for instance) into paths (Menu Path > Object to Path) and then select all objects and combine their paths (Menu Path > Combine (or compound? don't know the english entry) ctrl-K) then save. Then you can go to https://icomoon.io/app, import all svg icons, select them all, then generate the font. The `icomoon.woof` file you'll find in the zip is the one to use to actually replace `symbol-icons.woff` in the `icons/` directory. Also, the page will display the numbers (kind of addresses?) to use in `styles/symbols-tree-nav.less` like in these lines:

```
@symbol-class:    '\e900';
@symbol-struct:   '\e901';
@symbol-macro:    '\e906';
@symbol-typedef:  '\e908';
@symbol-union:    '\e909';
@symbol-interface:'\e904';
@symbol-enum:     '\e902';
@symbol-variable: '\e90a';
@symbol-function: '\e903';
@symbol-namespace:'\e907';
@symbol-library:  '\e905';
@symbol-source:   '\e90b';
```
In the same file, add the relevant lines to define the icons in classes correctly, like for instance for library and source:

```
.symbols-tree-nav .icon-library::before {
  .symbol-icon(symbol-library);
}

.symbols-tree-nav .icon-source::before {
  .symbol-icon(symbol-source);
}
```
Check the commits in dev branch to see all details, but that's not more than that.
In order to improve support for markdown, what remains is to add the relevant icons (like use a * instead of a {*} for the list items, add ##, ### for different headers) and play with the regex to add the detection of more headers and levels, and play with the scope syntax of universal ctags, like I described somewhat above for haxe, to get the list items included _inside_ heading symbols.

**Comment by nicolashainaux** [comment]
@liuderchi Working on these icons a little bit... and regarding the headers' ones, if we combine several sharp symbols, like in ### (for three levels), then the text entries will most likely be shifted to the right (not only because they're folded inside the levels above). Is this acceptable? Or should the icons all have the same width? In which case, the # should be reduced in order to make several ones fit into the same width as only one.

**Comment by liuderchi** [comment]
@nicolashainaux IMHO it's acceptable. :+1:

**Comment by liuderchi** [comment]
@nicolashainaux I came across this cool package [document-outline](https://atom.io/packages/document-outline)
hope this package can provide some ideas.
FYI

**Comment by nicolashainaux** [comment]
Well it's far better than symbols-tree-*. I rather work on ReStructured Text documents, and this plugin displays an excellent outline. The option "auto toggle on supported types" doesn't work fine, unfortunately (but I guess it should and will), so I wonder if this would not be an option to rather focus on add an option in symbols-tree-nav to auto-hide for certain types of documents (and/or auto-show on others), so either document you open, you get the right plugin showing up.

**Comment by nicolashainaux** [comment]
I've had a look in the source code, it seems the author(s) made it in resizable dock less than one year ago, so this might be interesting for issue #9 too.

**Comment by nicolashainaux** [comment]
@liuderchi Had you seen these PR? https://github.com/xndcn/symbols-tree-view/pull/176 and https://github.com/xndcn/symbols-tree-view/pull/177
I will add them both in the next patch release.

**Comment by liuderchi** [comment]
@nicolashainaux thanks for notifying me.
These are good news and I can't wait to use it.
