### ISSUE TITLE
Support for R language

### ISSUE THREAD

**Issue by nicolashainaux** [nicolashainaux/symbols-tree-nav#3]
I've cleaned the code to make the patch less dirty and added two icons, one for library, one for source. This way, I could get this:

![r_support](https://cloud.githubusercontent.com/assets/7633482/24786027/ab47f46a-1b5e-11e7-800e-c6adb394ad2f.png)

(though I added a custom color for source in the `.less` file:

```
.symbols-tree-nav {
  li.list-item {
    .icon-source {
      color: #73a86a;
    }
  }
}
```
)

It's always possible to right-click and check/uncheck any category, to see it or not (including library and source) and to define in the "AutoHide Types" setting which categories should be checked or unchecked by default.

This is in the dev branch and I intend to push it on master and publish it.

**Comment by carlosviansi** [comment]
Looks great! Sorry, should I just update to test again, or do you want me to follow other procedure?

**Comment by nicolashainaux** [comment]
I'll tell you here when I publish the next patch (next week I think), then you'll be able to test it. Just wanted to know whether this kind of output is still OK.

**Comment by nicolashainaux** [comment]
This is done. Tell me if there's a problem!

**Comment by nicolashainaux** [comment]
Looks like there's nothing wrong, so I close this issue now. Don't hesitate to tell if there's any problem.
