### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by mauricerkelly** [nicolashainaux/symbols-tree-nav#5]
As a followup to your comment on https://github.com/xndcn/symbols-tree-view/pull/167 I tried to fork your repo to add it there, but GitHub tells me I already have a fork of it (since I have a fork of your ancestor project). It may be best to wait and see if it gets pulled in there, and then pull it into your own fork. If it takes too long, I'll close my PR there and see if I can reopen it here.

**Comment by nicolashainaux** [comment]
Yes, that's fine! Thanks for your follow-up!
